export const PLAYLIST_FETCH_REQUEST = "PLAYLIST_FETCH_REQUEST"
export const PLAYLIST_FETCH_SUCCESS = "PLAYLIST_FETCH_SUCCESS"
export const PLAYLIST_FETCH_FAILURE = "PLAYLIST_FETCH_FAILURE"

export const PLAYLIST_UPDATE_REQUEST = "PLAYLIST_UPDATE_REQUEST"
export const MUSIC_PLAYER_REMOVE_QUEUE = "MUSIC_PLAYER_ADD_TO_QUEUE"
export const MUSIC_PLAYER_CLEAR_QUEUE = "MUSIC_PLAYER_ADD_TO_QUEUE"